---

version: '3'
services: 

  opensearch-node1:
    image: opensearchproject/opensearch:latest
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      - discovery.seed_hosts=opensearch-node1
      - cluster.initial_master_nodes=opensearch-node1
      - bootstrap.memory_lock=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 
        hard: 65536
    volumes:
      - opensearch-node1_data:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 
    networks:
      - opensearch-net



  fluentd: 
    build: .
    container_name: fluentd
    volumes: 
      - fluentd_buffer:/fluentd/buffer/:rw
    environment: 
      - "OPENSEARCH_HOST=opensearch-node1"
      - "OPENSEARCH_USER=admin"
      - "OPENSEARCH_PASS=admin"
      - "INFLUXDB_HOST=influxdb:8086"
      - "INFLUXDB_TOKEN=XXXXXX"
    ports: 
      - 5000:5000
    depends_on:
      - opensearch-node1
    networks:
      - opensearch-net
      - influxdb-net

  influxdb: 
    image: quay.io/influxdb/influxdb:v2.0.0
    container_name: influxdb
    volumes: 
      - influxdb_data:/var/lib/influxdb
    ports: 
      - 8086:8086
    networks: 
      - influxdb-net


networks: 
  opensearch-net: 
  influxdb-net: 
 
volumes: 
  opensearch-node1_data: 
  influxdb_data:
  grafana_data: 
  fluentd_buffer:
